name: Build AnimeLuxe APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # تحديث لـ v4 أيضاً للأمان

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # تحديث لـ v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew || true # إضافة true لتجنب الفشل إذا كان الملف غير موجود بعد

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # الحل للمشكلة التي ظهرت لك
        with:
          name: AnimeLuxe-Extension-APK
          path: src/build/outputs/apk/debug/*.apk
